sudo: false
language: scala
scala:
  - 2.11.11
  - 2.12.4
jdk:
  - oraclejdk8
services:
  - memcached
  - redis
script:
  - sbt +test
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
before_install:
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
