name: Test CI

on:
  pull_request:
    branches:
    - master

jobs:
  test-node:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run Node tests
      run: |
        cd node
        yarn
        yarn test --passWithNoTests
      env:
        CI: true
