sudo: false
language: node_js

notifications:
  email:
    on_success: never
    on_failure: never # change

script:
  - npm run lint
  # - npm run bundle
  - npm rm tslint
  - npm install $TYPESCRIPT --force
  # - npm run exec
  - npm run test

env:
  # - TYPESCRIPT=typescript@2.2
  - TYPESCRIPT=typescript@latest
  - TYPESCRIPT=typescript@next

node_js:
  - "stable"
