export const BASE_URL = 'http://vtexgame1.vtexlocal.com.br:3000/'
export const BASE_URL_COMPLETE = 'http://vtexgame1.vtexlocal.com.br/'
export const ADD_SKUS_ENDPOINT = 'checkout/cart/add?'
export const CHECKOUT_ENDPOINT = 'checkout/'
export const PROFILE_ENDPOINT = 'api/checkout/pub/profiles/'
