language: java

jdk:
  - openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

stages:
  - build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script: |
        mvn install -B

    - stage: release
      script: |
        docker login -u="$DOCKER_USER" -p="$DOCKER_PWD"
        cp .travis.settings.xml $HOME/.m2/settings.xml
        mvn deploy -B -Pdocker-release
